org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.230
neo_version_range=[21.1,22)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=mekv
mod_name=mekv
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.dasien
mod_authors=Dasien
mod_description=a mod for Dasien
